In [2]:
#coalcomsumption https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_coal.csv
#consumption_ng.csv https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_ng.csv
#consumption_nuclear.csv https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_nuclear.csv
#consumption_total.csv https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_total.csv
#consumption_total_renewable.csv  https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_total_renewable.csv
#prod_coal.csv  https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_coal.csv
#prod_ng.csv    https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_ng.csv
#prod_nuclear.csv   https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_nuclear.csv
#production_total.csv   https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/production_total.csv
#prod_total_renewable.csv    https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_total_renewable.csv

In [182]:
import pandas as pd

# --- Define URLs ---
urls = {
    "coal_consumption": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_coal.csv",
    "consumption_ng": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_ng.csv",
    "consumption_nuclear": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_nuclear.csv",
    "consumption_total": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_total.csv",
    "consumption_total_renewable": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/consumption_total_renewable.csv",
    "prod_coal": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_coal.csv",
    "prod_ng": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_ng.csv",
    "prod_nuclear": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_nuclear.csv",
    "production_total": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/production_total.csv",
    "prod_total_renewable": "https://raw.githubusercontent.com/greggmaloy/608/refs/heads/main/prod_total_renewable.csv"
}

# --- Load all CSVs into dictionary ---
dfs = {name: pd.read_csv(url) for name, url in urls.items()}

# --- Assign each DF to its own variable ---
coal_consumption_df = dfs["coal_consumption"]
ng_consumption_df = dfs["consumption_ng"]
nuclear_consumption_df = dfs["consumption_nuclear"]
total_consumption_df = dfs["consumption_total"]
renewable_consumption_df = dfs["consumption_total_renewable"]

coal_production_df = dfs["prod_coal"]
ng_production_df = dfs["prod_ng"]
nuclear_production_df = dfs["prod_nuclear"]
total_production_df = dfs["production_total"]
renewable_production_df = dfs["prod_total_renewable"]

# --- Print heads of each ---
print("Coal Consumption:\n", coal_consumption_df.head(), "\n")
print("Natural Gas Consumption:\n", ng_consumption_df.head(), "\n")
print("Nuclear Consumption:\n", nuclear_consumption_df.head(), "\n")
print("Total Consumption:\n", total_consumption_df.head(), "\n")
print("Renewable Consumption:\n", renewable_consumption_df.head(), "\n")

print("Coal Production:\n", coal_production_df.head(), "\n")
print("Natural Gas Production:\n", ng_production_df.head(), "\n")
print("Nuclear Production:\n", nuclear_production_df.head(), "\n")
print("Total Production:\n", total_production_df.head(), "\n")
print("Renewable Production:\n", renewable_production_df.head(), "\n")

Coal Consumption:
   State     1960     1961     1962     1963     1964     1965     1966  \
0    AK    7,189   11,552   13,559   11,999   12,029    9,888   16,431
1    AL  395,400  382,455  427,177  442,465  459,000  533,142  583,457
2    AR      356      275      160      135      186      163      111
3    AZ      210      211    6,291    8,432    9,103    7,030    7,373
4    CA   35,903   59,106   39,681   46,127   53,723   63,693   51,515

      1967     1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94  \
0   18,462   15,998  ...         NaN         NaN         NaN         NaN
1  580,163  618,335  ...         NaN         NaN         NaN         NaN
2      104      132  ...         NaN         NaN         NaN         NaN
3    7,184    8,137  ...         NaN         NaN         NaN         NaN
4   53,949   57,011  ...         NaN         NaN         NaN         NaN

  Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

Natural Gas Consumption:
   State       1960       1961       1962       1963       1964       1965  \
0    AK      2,034      2,300      4,048      5,567      6,805      7,670
1    AL    190,706    191,533    201,250    211,348    230,316    236,949
2    AR    222,202    215,311    235,477    252,846    278,852    277,661
3    AZ    140,275    159,093    163,461    169,533    174,623    166,063
4    CA  1,301,826  1,400,174  1,483,423  1,623,370  1,817,241  1,813,213

        1966       1967       1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93  \
0     12,282     11,889     17,636  ...         NaN         NaN         NaN
1    240,755    262,055    296,690  ...         NaN         NaN         NaN
2    289,632    295,756    321,569  ...         NaN         NaN         NaN
3    174,448    169,085    189,965  ...         NaN         NaN         NaN
4  1,982,305  2,048,734  2,187,260  ...         NaN         NaN         NaN

  Unnamed: 94 Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

  Unnamed: 100
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

[5 rows x 101 columns]

Nuclear Consumption:
   State 1960 1961 1962   1963   1964   1965   1966   1967    1968  ...  \
0    AK    0    0    0      0      0      0      0      0       0  ...
1    AL    0    0    0      0      0      0      0      0       0  ...
2    AR    0    0    0      0      0      0      0      0       0  ...
3    AZ    0    0    0      0      0      0      0      0       0  ...
4    CA    1   55   84  2,288  4,369  3,193  1,895  6,503  17,003  ...

  Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94 Unnamed: 95 Unnamed: 96  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

  Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

Total Consumption:
   State         1960         1961         1962         1963         1964  \
0   AK       59,303       70,020       76,642       78,488       82,793
1   AL      842,283      806,682      853,424      885,811      949,411
2   AR      417,153      423,192      446,994      474,761      515,874
3   AZ      273,431      294,660      313,581      337,213      357,961
4   CA    3,360,697    3,513,822    3,623,382    3,825,677    4,112,125

          1965         1966         1967         1968  ... Unnamed: 91  \
0      85,319      100,481      112,625      119,992   ...         NaN
1   1,011,125    1,055,347    1,100,904    1,208,038   ...         NaN
2     515,759      553,146      581,814      620,382   ...         NaN
3     362,858      390,820      400,280      442,172   ...         NaN
4   4,267,121    4,525,141    4,703,411    4,979,463   ...         NaN

  Unnamed: 92 Unnamed: 93 Unnamed: 94 Unnamed: 95 Unnamed: 96 Unnamed: 97  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

  Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN          NaN
1         NaN         NaN          NaN
2         NaN         NaN          NaN
3         NaN         NaN          NaN
4         NaN         NaN          NaN

[5 rows x 101 columns]

Renewable Consumption:
   State     1960     1961     1962     1963     1964     1965     1966  \
0    AK    4,670    5,160    5,283    5,493    5,828    6,057    6,114
1    AL   66,967   69,190   71,684   67,547   76,231   71,876   72,734
2    AR   40,817   41,049   40,059   38,411   38,775   38,819   40,584
3    AZ   14,214   13,847   13,645   14,064   13,932   18,841   21,495
4    CA  141,733  136,263  165,152  180,034  174,530  202,276  190,831

      1967     1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94  \
0    5,910    5,946  ...         NaN         NaN         NaN         NaN
1   80,231   78,106  ...         NaN         NaN         NaN         NaN
2   37,500   43,993  ...         NaN         NaN         NaN         NaN
3   21,267   23,609  ...         NaN         NaN         NaN         NaN
4  223,328  204,480  ...         NaN         NaN         NaN         NaN

  Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

Coal Production:
   State     1960     1961     1962     1963     1964     1965     1966  \
0    AK   11,263   11,497   13,588   13,307   11,622   13,931   14,461
1    AL  318,818  316,466  315,608  302,842  353,712  363,440  348,419
2    AR    9,178    8,864    5,745    4,959    4,757    5,071    5,296
3    AZ      132        0        0        0        0        0        0
4    CA        0        0        0        0        0        0        0

      1967     1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94  \
0   14,430   11,700  ...         NaN         NaN         NaN         NaN
1  379,465  402,842  ...         NaN         NaN         NaN         NaN
2    4,241    4,735  ...         NaN         NaN         NaN         NaN
3       22        0  ...         NaN         NaN         NaN         NaN
4        0        0  ...         NaN         NaN         NaN         NaN

  Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

Natural Gas Production:
   State     1960     1961     1962     1963     1964     1965     1966  \
0    AK      248      637    2,205    4,541    6,332    7,324   11,374
1    AL       93       91      208      288      270      330      410
2    AR   57,339   61,574   68,467   78,691   78,760   85,651  108,754
3    AZ        0        0      244    1,413    2,144    3,289    3,347
4    CA  589,797  633,908  643,001  736,753  756,771  752,592  785,895

      1967     1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94  \
0   14,575   17,508  ...         NaN         NaN         NaN         NaN
1      403      374  ...         NaN         NaN         NaN         NaN
2  120,488  161,958  ...         NaN         NaN         NaN         NaN
3    1,329      933  ...         NaN         NaN         NaN         NaN
4  776,178  814,712  ...         NaN         NaN         NaN         NaN

  Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

Nuclear Production:
   State 1960 1961 1962   1963   1964   1965   1966   1967    1968  ...  \
0    AK    0    0    0      0      0      0      0      0       0  ...
1    AL    0    0    0      0      0      0      0      0       0  ...
2    AR    0    0    0      0      0      0      0      0       0  ...
3    AZ    0    0    0      0      0      0      0      0       0  ...
4    CA    1   55   84  2,288  4,369  3,193  1,895  6,503  17,003  ...

  Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94 Unnamed: 95 Unnamed: 96  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

  Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

Total Production:
   State       1960       1961       1962       1963       1964       1965  \
0    AK     19,424     53,991     80,577     85,632     87,924     91,854
1    AL    428,386    425,947    430,844    423,892    479,502    482,417
2    AR    282,012    281,113    274,635    281,016    277,366    279,935
3    AZ     14,769     14,271     14,115     15,871     16,448     22,693
4    CA  2,502,572  2,507,958  2,528,459  2,664,342  2,675,722  2,793,343

        1966       1967       1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93  \
0    115,226    203,846    419,137  ...         NaN         NaN         NaN
1    468,137    502,718    525,604  ...         NaN         NaN         NaN
2    292,813    284,465    323,577  ...         NaN         NaN         NaN
3     25,608     39,577     44,088  ...         NaN         NaN         NaN
4  2,981,332  3,089,479  3,202,042  ...         NaN         NaN         NaN

  Unnamed: 94 Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

  Unnamed: 100
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

[5 rows x 101 columns]

Renewable Production:
   State     1960     1961     1962     1963     1964     1965     1966  \
0    AK    4,670    5,160    5,283    5,493    5,828    6,057    6,114
1    AL   66,967   69,190   71,684   67,547   76,231   71,876   72,734
2    AR   40,817   41,049   40,059   38,411   38,775   38,819   40,584
3    AZ   14,214   13,847   13,645   14,064   13,932   18,841   21,495
4    CA  141,733  136,263  165,152  180,034  174,530  202,276  190,831

      1967     1968  ... Unnamed: 91 Unnamed: 92 Unnamed: 93 Unnamed: 94  \
0    5,910    5,946  ...         NaN         NaN         NaN         NaN
1   80,231   78,106  ...         NaN         NaN         NaN         NaN
2   37,500   43,993  ...         NaN         NaN         NaN         NaN
3   21,267   23,609  ...         NaN         NaN         NaN         NaN
4  223,328  204,480  ...         NaN         NaN         NaN         NaN

  Unnamed: 95 Unnamed: 96 Unnamed: 97 Unnamed: 98 Unnamed: 99 Unnamed: 100
0         NaN         NaN         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN         NaN         NaN          NaN

[5 rows x 101 columns]

In [184]:
# Function to keep only State and 2023 columns
def keep_state_2023(df):
    return df.loc[:, ["State", "2023"]]

coal_consumption_2023 = keep_state_2023(coal_consumption_df)
ng_consumption_2023 = keep_state_2023(ng_consumption_df)
nuclear_consumption_2023 = keep_state_2023(nuclear_consumption_df)
total_consumption_2023 = keep_state_2023(total_consumption_df)
renewable_consumption_2023 = keep_state_2023(renewable_consumption_df)

coal_production_2023 = keep_state_2023(coal_production_df)
ng_production_2023 = keep_state_2023(ng_production_df)
nuclear_production_2023 = keep_state_2023(nuclear_production_df)
total_production_2023 = keep_state_2023(total_production_df)
renewable_production_2023 = keep_state_2023(renewable_production_df)

In [186]:
coal_consumption_2023.head()
ng_consumption_2023.head()
nuclear_consumption_2023.head() 
total_consumption_2023.head() 
renewable_consumption_2023.head()
coal_production_2023.head()
ng_production_2023.head()
nuclear_production_2023.head()
total_production_2023.head()
renewable_production_2023.head()

  State     2023
0    AK   10,087
1    AL  210,398
2    AR   90,359
3    AZ   81,595
4    CA  634,319

In [188]:
#cleanup

In [190]:
#cleanup some obs in 'state' are not present in each file.
print("coal_consumption_df rows:", len(dfs["coal_consumption"]))
print("ng_consumption_df rows:", len(dfs["consumption_ng"]))
print("nuclear_consumption_df rows:", len(dfs["consumption_nuclear"]))
print("total_consumption_df rows:", len(dfs["consumption_total"]))
print("renewable_consumption_df rows:", len(dfs["consumption_total_renewable"]))

print("coal_production_df rows:", len(dfs["prod_coal"]))
print("ng_production_df rows:", len(dfs["prod_ng"]))
print("nuclear_production_df rows:", len(dfs["prod_nuclear"]))
print("total_production_df rows:", len(dfs["production_total"]))
print("renewable_production_df rows:", len(dfs["prod_total_renewable"]))

coal_consumption_df rows: 52
ng_consumption_df rows: 52
nuclear_consumption_df rows: 52
total_consumption_df rows: 53
renewable_consumption_df rows: 52
coal_production_df rows: 52
ng_production_df rows: 53
nuclear_production_df rows: 52
total_production_df rows: 54
renewable_production_df rows: 52

In [193]:
dfs_2023 = {
    "coal_consumption_2023": coal_consumption_2023,
    "ng_consumption_2023": ng_consumption_2023,
    "nuclear_consumption_2023": nuclear_consumption_2023,
    "total_consumption_2023": total_consumption_2023,
    "renewable_consumption_2023": renewable_consumption_2023,
    
    "coal_production_2023": coal_production_2023,
    "ng_production_2023": ng_production_2023,
    "nuclear_production_2023": nuclear_production_2023,
    "total_production_2023": total_production_2023,
    "renewable_production_2023": renewable_production_2023
}

for name, df in dfs_2023.items():
    print(f"\n===== Summary Statistics: {name} =====")
    print(df.describe(include='all'))

===== Summary Statistics: coal_consumption_2023 =====
       State 2023
count     52   52
unique    52   46
top       AK    0
freq       1    7

===== Summary Statistics: ng_consumption_2023 =====
       State     2023
count     52       52
unique    52       52
top       AK  448,087
freq       1        1

===== Summary Statistics: nuclear_consumption_2023 =====
       State 2023
count     52   52
unique    52   30
top       AK    0
freq       1   23

===== Summary Statistics: total_consumption_2023 =====
       State       2023
count     52         52
unique    52         52
top      AK    746,978
freq       1          1

===== Summary Statistics: renewable_consumption_2023 =====
       State    2023
count     52      52
unique    52      52
top       AK  10,087
freq       1       1

===== Summary Statistics: coal_production_2023 =====
       State 2023
count     52   52
unique    52   23
top       AK    0
freq       1   30

===== Summary Statistics: ng_production_2023 =====
       State 2023
count     53   53
unique    53   36
top       AK    0
freq       1   18

===== Summary Statistics: nuclear_production_2023 =====
       State 2023
count     52   52
unique    52   30
top       AK    0
freq       1   23

===== Summary Statistics: total_production_2023 =====
       State       2023
count     54         54
unique    54         54
top       AK  1,320,750
freq       1          1

===== Summary Statistics: renewable_production_2023 =====
       State    2023
count     52      52
unique    52      52
top       AK  10,087
freq       1       1

In [195]:
dfs_2023 = {
    "coal_consumption_2023": coal_consumption_2023,
    "ng_consumption_2023": ng_consumption_2023,
    "nuclear_consumption_2023": nuclear_consumption_2023,
    "total_consumption_2023": total_consumption_2023,
    "renewable_consumption_2023": renewable_consumption_2023,

    "coal_production_2023": coal_production_2023,
    "ng_production_2023": ng_production_2023,
    "nuclear_production_2023": nuclear_production_2023,
    "total_production_2023": total_production_2023,
    "renewable_production_2023": renewable_production_2023
}

# Rename 2023 column in each dataframe to its dictionary key
for name, df in dfs_2023.items():
    if "2023" in df.columns:
        df.rename(columns={"2023": name}, inplace=True)

In [197]:
dfs_2023 = {
    "coal_consumption_2023": coal_consumption_2023,
    "ng_consumption_2023": ng_consumption_2023,
    "nuclear_consumption_2023": nuclear_consumption_2023,
    "total_consumption_2023": total_consumption_2023,
    "renewable_consumption_2023": renewable_consumption_2023,
    
    "coal_production_2023": coal_production_2023,
    "ng_production_2023": ng_production_2023,
    "nuclear_production_2023": nuclear_production_2023,
    "total_production_2023": total_production_2023,
    "renewable_production_2023": renewable_production_2023
}

for name, df in dfs_2023.items():
    print(f"\n===== Summary Statistics: {name} =====")
    print(df.describe(include='all'))

===== Summary Statistics: coal_consumption_2023 =====
       State coal_consumption_2023
count     52                    52
unique    52                    46
top       AK                     0
freq       1                     7

===== Summary Statistics: ng_consumption_2023 =====
       State ng_consumption_2023
count     52                  52
unique    52                  52
top       AK             448,087
freq       1                   1

===== Summary Statistics: nuclear_consumption_2023 =====
       State nuclear_consumption_2023
count     52                       52
unique    52                       30
top       AK                        0
freq       1                       23

===== Summary Statistics: total_consumption_2023 =====
       State total_consumption_2023
count     52                     52
unique    52                     52
top      AK                746,978
freq       1                      1

===== Summary Statistics: renewable_consumption_2023 =====
       State renewable_consumption_2023
count     52                         52
unique    52                         52
top       AK                     10,087
freq       1                          1

===== Summary Statistics: coal_production_2023 =====
       State coal_production_2023
count     52                   52
unique    52                   23
top       AK                    0
freq       1                   30

===== Summary Statistics: ng_production_2023 =====
       State ng_production_2023
count     53                 53
unique    53                 36
top       AK                  0
freq       1                 18

===== Summary Statistics: nuclear_production_2023 =====
       State nuclear_production_2023
count     52                      52
unique    52                      30
top       AK                       0
freq       1                      23

===== Summary Statistics: total_production_2023 =====
       State total_production_2023
count     54                    54
unique    54                    54
top       AK             1,320,750
freq       1                     1

===== Summary Statistics: renewable_production_2023 =====
       State renewable_production_2023
count     52                        52
unique    52                        52
top       AK                    10,087
freq       1                         1

In [199]:
# Dictionary of the dataframes
dfs_2023 = {
    "coal_consumption_2023": coal_consumption_2023,
    "ng_consumption_2023": ng_consumption_2023,
    "nuclear_consumption_2023": nuclear_consumption_2023,
    "total_consumption_2023": total_consumption_2023,
    "renewable_consumption_2023": renewable_consumption_2023,

    "coal_production_2023": coal_production_2023,
    "ng_production_2023": ng_production_2023,
    "nuclear_production_2023": nuclear_production_2023,
    "renewable_production_2023": renewable_production_2023
}

# Start with total_production_2023 as the base
merged_df = total_production_2023.copy()

# Merge each df into merged_df
for name, df in dfs_2023.items():
    merged_df = merged_df.merge(df, on="State", how="left")

merged_df.head()

,State,total_production_2023,coal_consumption_2023,ng_consumption_2023,nuclear_consumption_2023,total_consumption_2023,renewable_consumption_2023,coal_production_2023,ng_production_2023,nuclear_production_2023,renewable_production_2023
0,AK,"1,320,750","18,414","448,087",0,NaN,"10,087","15,496","410,727",0,"10,087"
1,AL,"1,103,247","224,926","775,747","476,392",NaN,"222,189","303,503","92,525","476,392","210,398"
2,AR,"671,299","180,262","399,566","156,492",NaN,"87,277",0,"399,132","156,492","90,359"
3,AZ,"411,139","137,885","537,151","329,474",NaN,"108,445",0,30,"329,474","81,595"
4,CA,"1,641,594","28,746","2,154,533","185,192",NaN,"1,065,179",0,"148,926","185,192","634,319"

In [201]:
# Dictionary of the dataframes
dfs_2023 = {
    "coal_consumption_2023": coal_consumption_2023,
    "ng_consumption_2023": ng_consumption_2023,
    "nuclear_consumption_2023": nuclear_consumption_2023,
    "total_consumption_2023": total_consumption_2023,
    "renewable_consumption_2023": renewable_consumption_2023,

    "coal_production_2023": coal_production_2023,
    "ng_production_2023": ng_production_2023,
    "nuclear_production_2023": nuclear_production_2023,
    "renewable_production_2023": renewable_production_2023
}

# Start with total_production_2023 as the base
merged_df = total_production_2023.copy()

# Merge each df into merged_df
for name, df in dfs_2023.items():
    merged_df = merged_df.merge(df, on="State", how="left")

merged_df.head()

,State,total_production_2023,coal_consumption_2023,ng_consumption_2023,nuclear_consumption_2023,total_consumption_2023,renewable_consumption_2023,coal_production_2023,ng_production_2023,nuclear_production_2023,renewable_production_2023
0,AK,"1,320,750","18,414","448,087",0,NaN,"10,087","15,496","410,727",0,"10,087"
1,AL,"1,103,247","224,926","775,747","476,392",NaN,"222,189","303,503","92,525","476,392","210,398"
2,AR,"671,299","180,262","399,566","156,492",NaN,"87,277",0,"399,132","156,492","90,359"
3,AZ,"411,139","137,885","537,151","329,474",NaN,"108,445",0,30,"329,474","81,595"
4,CA,"1,641,594","28,746","2,154,533","185,192",NaN,"1,065,179",0,"148,926","185,192","634,319"

In [203]:
total_consumption_2023
total_production_2023

   State total_production_2023
0     AK             1,320,750
1     AL             1,103,247
2     AR               671,299
3     AZ               411,139
4     CA             1,641,594
5     CO             3,559,311
6     CT               177,908
7     DC                 1,825
8     DE                 3,315
9     FL               531,607
10    GA               660,624
11    HI                17,524
12    IA               782,941
13    ID                76,920
14    IL             2,201,058
15    IN               808,997
16    KS               614,156
17    KY               850,473
18    LA             4,997,731
19    MA                57,820
20    MD               217,026
21    ME                82,781
22    MI               580,412
23    MN               428,651
24    MO               210,003
25    MS               313,726
26    MT               767,125
27    NC               614,879
28    ND             4,491,856
29    NE               401,345
30    NH               132,967
31    NJ               335,370
32    NM             7,651,766
33    NV                65,997
34    NY               516,805
35    OH             3,001,427
36    OK             4,393,809
37    OR               192,922
38    PA            10,101,804
39    RI                 8,863
40    SC               705,705
41    SD               235,952
42    TN               501,599
43    TX            27,104,730
44    UT               825,655
45    VA               834,458
46    VT                19,612
47    WA               440,429
48    WI               275,057
49    WV             6,089,936
50    WY             5,845,631
51    X3             4,736,995
52    X5                17,175
53    US           102,670,531

In [205]:
print("total_consumption_2023 dtypes:")
print(total_consumption_2023.dtypes)

print("\ntotal_production_2023 dtypes:")
print(total_production_2023.dtypes)

total_consumption_2023 dtypes:
State                     object
total_consumption_2023    object
dtype: object

total_production_2023 dtypes:
State                    object
total_production_2023    object
dtype: object

In [207]:
dfs_2023 = [
    coal_consumption_2023,
    ng_consumption_2023,
    nuclear_consumption_2023,
    total_consumption_2023,
    renewable_consumption_2023,
    coal_production_2023,
    ng_production_2023,
    nuclear_production_2023,
    total_production_2023,
    renewable_production_2023
]

for df in dfs_2023:
    df.columns = (df.columns
                  .str.strip()
                  .str.replace(" ", "_", regex=False))

In [209]:
total_consumption_2023

   State total_consumption_2023
0    AK                746,978
1    AL              1,860,171
2    AR              1,049,897
3    AZ              1,526,567
4    CA              6,816,746
5    CO              1,368,260
6    CT                688,978
7    DC                135,231
8    DE                268,494
9    FL              4,301,743
10   GA              2,838,817
11   HI                272,874
12   IA              1,405,284
13   ID                505,344
14   IL              3,486,989
15   IN              2,555,897
16   KS                973,356
17   KY              1,611,130
18   LA              4,166,787
19   MA              1,282,732
20   MD              1,182,581
21   ME                328,596
22   MI              2,543,241
23   MN              1,689,356
24   MO              1,681,954
25   MS              1,074,319
26   MT                382,218
27   NC              2,472,784
28   ND                703,926
29   NE                840,136
30   NH                294,907
31   NJ              1,982,296
32   NM                680,489
33   NV                689,433
34   NY              3,436,991
35   OH              3,381,273
36   OK              1,519,146
37   OR                875,020
38   PA              3,607,506
39   RI                182,950
40   SC              1,603,946
41   SD                347,163
42   TN              2,058,049
43   TX             14,137,451
44   UT                853,951
45   VA              2,435,265
46   VT                113,104
47   WA              1,602,662
48   WI              1,656,177
49   WV                832,806
50   WY                499,766
51   US             93,557,489
52   NaN                    NaN

In [211]:
total_consumption_2023["State"] = (
    total_consumption_2023["State"]
        .astype(str)          # make sure it’s string
        .str.strip()          # remove leading/trailing spaces
        .str.replace(r"\s+", "", regex=True)  # remove ANY internal spaces
)

In [213]:

#Dictionary of the dataframes
dfs_2023 = {
    "coal_consumption_2023": coal_consumption_2023,
    "ng_consumption_2023": ng_consumption_2023,
    "nuclear_consumption_2023": nuclear_consumption_2023,
    "total_consumption_2023": total_consumption_2023,
    "renewable_consumption_2023": renewable_consumption_2023,

    "coal_production_2023": coal_production_2023,
    "ng_production_2023": ng_production_2023,
    "nuclear_production_2023": nuclear_production_2023,
    "renewable_production_2023": renewable_production_2023
}

# Start with total_production_2023 as the base
merged_df = total_production_2023.copy()

# Merge each df into merged_df
for name, df in dfs_2023.items():
    merged_df = merged_df.merge(df, on="State", how="left")

merged_df.head()

,State,total_production_2023,coal_consumption_2023,ng_consumption_2023,nuclear_consumption_2023,total_consumption_2023,renewable_consumption_2023,coal_production_2023,ng_production_2023,nuclear_production_2023,renewable_production_2023
0,AK,"1,320,750","18,414","448,087",0,"746,978","10,087","15,496","410,727",0,"10,087"
1,AL,"1,103,247","224,926","775,747","476,392","1,860,171","222,189","303,503","92,525","476,392","210,398"
2,AR,"671,299","180,262","399,566","156,492","1,049,897","87,277",0,"399,132","156,492","90,359"
3,AZ,"411,139","137,885","537,151","329,474","1,526,567","108,445",0,30,"329,474","81,595"
4,CA,"1,641,594","28,746","2,154,533","185,192","6,816,746","1,065,179",0,"148,926","185,192","634,319"

In [215]:
merged_df[[
    "total_consumption_2023",
    "total_production_2023",
    "coal_production_2023",
    "ng_production_2023",
    "nuclear_production_2023",
    "renewable_production_2023"
]].dtypes

total_consumption_2023       object
total_production_2023        object
coal_production_2023         object
ng_production_2023           object
nuclear_production_2023      object
renewable_production_2023    object
dtype: object

In [217]:
# Convert every column except "State" to numeric
for col in merged_df.columns:
    if col != "State":
        merged_df[col] = (
            merged_df[col]
            .astype(str)
            .str.strip()
            .str.replace(",", "", regex=False)
        )
        merged_df[col] = pd.to_numeric(merged_df[col], errors="coerce")

In [219]:
merged_df.dtypes

State                          object
total_production_2023           int64
coal_consumption_2023         float64
ng_consumption_2023           float64
nuclear_consumption_2023      float64
total_consumption_2023        float64
renewable_consumption_2023    float64
coal_production_2023          float64
ng_production_2023            float64
nuclear_production_2023       float64
renewable_production_2023     float64
dtype: object

In [221]:
merged_df["total_ratio"] = (
    merged_df["total_consumption_2023"] /
    merged_df["total_production_2023"].replace({0: np.nan})
)
merged_df

,State,total_production_2023,coal_consumption_2023,ng_consumption_2023,nuclear_consumption_2023,total_consumption_2023,renewable_consumption_2023,coal_production_2023,ng_production_2023,nuclear_production_2023,renewable_production_2023,total_ratio
0,AK,1320750,18414.0,448087.0,0.0,746978.0,10087.0,15496.0,410727.0,0.0,10087.0,0.565571
1,AL,1103247,224926.0,775747.0,476392.0,1860171.0,222189.0,303503.0,92525.0,476392.0,210398.0,1.686088
2,AR,671299,180262.0,399566.0,156492.0,1049897.0,87277.0,0.0,399132.0,156492.0,90359.0,1.563978
3,AZ,411139,137885.0,537151.0,329474.0,1526567.0,108445.0,0.0,30.0,329474.0,81595.0,3.713019
4,CA,1641594,28746.0,2154533.0,185192.0,6816746.0,1065179.0,0.0,148926.0,185192.0,634319.0,4.152516
5,CO,3559311,204826.0,525446.0,0.0,1368260.0,115061.0,256169.0,2245754.0,0.0,108520.0,0.384417
6,CT,177908,0.0,304924.0,142873.0,688978.0,48981.0,0.0,0.0,142873.0,35034.0,3.872665
7,DC,1825,0.0,26236.0,0.0,135231.0,2795.0,0.0,0.0,0.0,1825.0,74.099178
8,DE,3315,338.0,84387.0,0.0,268494.0,8041.0,0.0,0.0,0.0,3315.0,80.993665
9,FL,531607,129387.0,1673836.0,312935.0,4301743.0,286306.0,0.0,727.0,312935.0,212130.0,8.091961
10,GA,660624,177521.0,787361.0,390663.0,2838817.0,291462.0,0.0,0.0,390663.0,269961.0,4.297175
11,HI,17524,0.0,152.0,0.0,272874.0,21046.0,0.0,0.0,0.0,17524.0,15.571445
12,IA,782941,201276.0,446677.0,0.0,1405284.0,414801.0,0.0,0.0,0.0,782941.0,1.794879
13,ID,76920,1144.0,154150.0,0.0,505344.0,77128.0,0.0,2554.0,0.0,74178.0,6.569735
14,IL,2201058,342683.0,1101064.0,1019691.0,3486989.0,245703.0,796247.0,2741.0,1019691.0,343170.0,1.584233
15,IN,808997,613533.0,921814.0,0.0,2555897.0,172891.0,539129.0,4013.0,0.0,257150.0,3.159341
16,KS,614156,184614.0,309427.0,107675.0,973356.0,140268.0,0.0,160886.0,107675.0,188174.0,1.584868
17,KY,850473,481815.0,369986.0,0.0,1611130.0,72603.0,677470.0,102640.0,0.0,59690.0,1.894393
18,LA,4997731,58224.0,2055504.0,127634.0,4166787.0,138982.0,4326.0,4423567.0,127634.0,247532.0,0.833736
19,MA,57820,0.0,386946.0,0.0,1282732.0,81559.0,0.0,0.0,0.0,57820.0,22.184919
20,MD,217026,30349.0,304669.0,156610.0,1182581.0,53711.0,30335.0,3.0,156610.0,30078.0,5.449029
21,ME,82781,1295.0,61045.0,0.0,328596.0,89444.0,0.0,0.0,0.0,82781.0,3.969462
22,MI,580412,287490.0,1104234.0,292615.0,2543241.0,198459.0,0.0,72824.0,292615.0,187472.0,4.381786
23,MN,428651,148968.0,536789.0,124626.0,1689356.0,223864.0,0.0,0.0,124626.0,304025.0,3.941099
24,MO,210003,442901.0,316512.0,95947.0,1681954.0,90412.0,3087.0,0.0,95947.0,110610.0,8.009190
25,MS,313726,49606.0,630107.0,122807.0,1074319.0,67305.0,27466.0,27937.0,122807.0,63977.0,3.424386
26,MT,767125,130059.0,96777.0,0.0,382218.0,58470.0,520661.0,45261.0,0.0,72382.0,0.498247
27,NC,614879,153784.0,662302.0,442493.0,2472784.0,186804.0,0.0,0.0,442493.0,172386.0,4.021578
28,ND,4491856,325716.0,220768.0,0.0,703926.0,92154.0,320145.0,1555143.0,0.0,160536.0,0.156712
29,NE,401345,195602.0,206276.0,72391.0,840136.0,164502.0,0.0,280.0,72391.0,319316.0,2.093301
30,NH,132967,1838.0,59589.0,99658.0,294907.0,38988.0,0.0,0.0,99658.0,33309.0,2.217896
31,NJ,335370,0.0,721282.0,296162.0,1982296.0,74408.0,0.0,0.0,296162.0,39207.0,5.910773
32,NM,7651766,75182.0,337083.0,0.0,680489.0,80278.0,147100.0,3634458.0,0.0,83883.0,0.088932
33,NV,65997,29284.0,301655.0,0.0,689433.0,74878.0,0.0,4.0,0.0,64821.0,10.446429
34,NY,516805,4823.0,1346622.0,287690.0,3436991.0,272967.0,0.0,8482.0,287690.0,219205.0,6.650460
35,OH,3001427,413577.0,1448857.0,169392.0,3381273.0,153083.0,46592.0,2451692.0,169392.0,163673.0,1.126555
36,OK,4393809,63787.0,860217.0,0.0,1519146.0,185378.0,40.0,3319920.0,0.0,181944.0,0.345747
37,OR,192922,652.0,327164.0,0.0,875020.0,236062.0,0.0,97.0,0.0,192825.0,4.535615
38,PA,10101804,307604.0,1937041.0,787083.0,3607506.0,178035.0,1122315.0,8013558.0,787083.0,151449.0,0.357115
39,RI,8863,0.0,112499.0,0.0,182950.0,13579.0,0.0,0.0,0.0,8863.0,20.641995
40,SC,705705,162323.0,346881.0,581365.0,1603946.0,142486.0,0.0,0.0,581365.0,124341.0,2.272828
41,SD,235952,22246.0,99752.0,0.0,347163.0,126540.0,0.0,135.0,0.0,230646.0,1.471329
42,TN,501599,202367.0,396870.0,396522.0,2058049.0,115678.0,0.0,3103.0,396522.0,100990.0,4.102977
43,TX,27104730,805600.0,5284670.0,425186.0,14137451.0,791211.0,182181.0,14311730.0,425186.0,742124.0,0.521586
44,UT,825655,174315.0,298976.0,0.0,853951.0,39674.0,156571.0,318533.0,0.0,29458.0,1.034271
45,VA,834458,46785.0,655997.0,310037.0,2435265.0,183979.0,282790.0,87638.0,310037.0,153971.0,2.918379
46,VT,19612,0.0,13001.0,0.0,113104.0,22209.0,0.0,0.0,0.0,19612.0,5.767081
47,WA,440429,49523.0,403038.0,88163.0,1602662.0,365956.0,0.0,0.0,88163.0,352266.0,3.638866
48,WI,275057,219995.0,565025.0,101204.0,1656177.0,150965.0,0.0,0.0,101204.0,173853.0,6.021214
49,WV,6089936,472309.0,309019.0,0.0,832806.0,28370.0,2201825.0,3762937.0,0.0,19557.0,0.136751
50,WY,5845631,366098.0,181395.0,0.0,499766.0,38474.0,4133004.0,1105416.0,0.0,56163.0,0.085494
51,X3,4736995,NaN,NaN,NaN,NaN,NaN,NaN,864135.0,NaN,NaN,NaN
52,X5,17175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,US,102670531,8169673.0,33609104.0,8098974.0,93557489.0,8187317.0,11766453.0,47577507.0,8098974.0,8369270.0,0.911240

In [223]:
merged_df["total_ratio_capped"] = merged_df["total_ratio"].clip(upper=5)
merged_df

,State,total_production_2023,coal_consumption_2023,ng_consumption_2023,nuclear_consumption_2023,total_consumption_2023,renewable_consumption_2023,coal_production_2023,ng_production_2023,nuclear_production_2023,renewable_production_2023,total_ratio,total_ratio_capped
0,AK,1320750,18414.0,448087.0,0.0,746978.0,10087.0,15496.0,410727.0,0.0,10087.0,0.565571,0.565571
1,AL,1103247,224926.0,775747.0,476392.0,1860171.0,222189.0,303503.0,92525.0,476392.0,210398.0,1.686088,1.686088
2,AR,671299,180262.0,399566.0,156492.0,1049897.0,87277.0,0.0,399132.0,156492.0,90359.0,1.563978,1.563978
3,AZ,411139,137885.0,537151.0,329474.0,1526567.0,108445.0,0.0,30.0,329474.0,81595.0,3.713019,3.713019
4,CA,1641594,28746.0,2154533.0,185192.0,6816746.0,1065179.0,0.0,148926.0,185192.0,634319.0,4.152516,4.152516
5,CO,3559311,204826.0,525446.0,0.0,1368260.0,115061.0,256169.0,2245754.0,0.0,108520.0,0.384417,0.384417
6,CT,177908,0.0,304924.0,142873.0,688978.0,48981.0,0.0,0.0,142873.0,35034.0,3.872665,3.872665
7,DC,1825,0.0,26236.0,0.0,135231.0,2795.0,0.0,0.0,0.0,1825.0,74.099178,5.000000
8,DE,3315,338.0,84387.0,0.0,268494.0,8041.0,0.0,0.0,0.0,3315.0,80.993665,5.000000
9,FL,531607,129387.0,1673836.0,312935.0,4301743.0,286306.0,0.0,727.0,312935.0,212130.0,8.091961,5.000000
10,GA,660624,177521.0,787361.0,390663.0,2838817.0,291462.0,0.0,0.0,390663.0,269961.0,4.297175,4.297175
11,HI,17524,0.0,152.0,0.0,272874.0,21046.0,0.0,0.0,0.0,17524.0,15.571445,5.000000
12,IA,782941,201276.0,446677.0,0.0,1405284.0,414801.0,0.0,0.0,0.0,782941.0,1.794879,1.794879
13,ID,76920,1144.0,154150.0,0.0,505344.0,77128.0,0.0,2554.0,0.0,74178.0,6.569735,5.000000
14,IL,2201058,342683.0,1101064.0,1019691.0,3486989.0,245703.0,796247.0,2741.0,1019691.0,343170.0,1.584233,1.584233
15,IN,808997,613533.0,921814.0,0.0,2555897.0,172891.0,539129.0,4013.0,0.0,257150.0,3.159341,3.159341
16,KS,614156,184614.0,309427.0,107675.0,973356.0,140268.0,0.0,160886.0,107675.0,188174.0,1.584868,1.584868
17,KY,850473,481815.0,369986.0,0.0,1611130.0,72603.0,677470.0,102640.0,0.0,59690.0,1.894393,1.894393
18,LA,4997731,58224.0,2055504.0,127634.0,4166787.0,138982.0,4326.0,4423567.0,127634.0,247532.0,0.833736,0.833736
19,MA,57820,0.0,386946.0,0.0,1282732.0,81559.0,0.0,0.0,0.0,57820.0,22.184919,5.000000
20,MD,217026,30349.0,304669.0,156610.0,1182581.0,53711.0,30335.0,3.0,156610.0,30078.0,5.449029,5.000000
21,ME,82781,1295.0,61045.0,0.0,328596.0,89444.0,0.0,0.0,0.0,82781.0,3.969462,3.969462
22,MI,580412,287490.0,1104234.0,292615.0,2543241.0,198459.0,0.0,72824.0,292615.0,187472.0,4.381786,4.381786
23,MN,428651,148968.0,536789.0,124626.0,1689356.0,223864.0,0.0,0.0,124626.0,304025.0,3.941099,3.941099
24,MO,210003,442901.0,316512.0,95947.0,1681954.0,90412.0,3087.0,0.0,95947.0,110610.0,8.009190,5.000000
25,MS,313726,49606.0,630107.0,122807.0,1074319.0,67305.0,27466.0,27937.0,122807.0,63977.0,3.424386,3.424386
26,MT,767125,130059.0,96777.0,0.0,382218.0,58470.0,520661.0,45261.0,0.0,72382.0,0.498247,0.498247
27,NC,614879,153784.0,662302.0,442493.0,2472784.0,186804.0,0.0,0.0,442493.0,172386.0,4.021578,4.021578
28,ND,4491856,325716.0,220768.0,0.0,703926.0,92154.0,320145.0,1555143.0,0.0,160536.0,0.156712,0.156712
29,NE,401345,195602.0,206276.0,72391.0,840136.0,164502.0,0.0,280.0,72391.0,319316.0,2.093301,2.093301
30,NH,132967,1838.0,59589.0,99658.0,294907.0,38988.0,0.0,0.0,99658.0,33309.0,2.217896,2.217896
31,NJ,335370,0.0,721282.0,296162.0,1982296.0,74408.0,0.0,0.0,296162.0,39207.0,5.910773,5.000000
32,NM,7651766,75182.0,337083.0,0.0,680489.0,80278.0,147100.0,3634458.0,0.0,83883.0,0.088932,0.088932
33,NV,65997,29284.0,301655.0,0.0,689433.0,74878.0,0.0,4.0,0.0,64821.0,10.446429,5.000000
34,NY,516805,4823.0,1346622.0,287690.0,3436991.0,272967.0,0.0,8482.0,287690.0,219205.0,6.650460,5.000000
35,OH,3001427,413577.0,1448857.0,169392.0,3381273.0,153083.0,46592.0,2451692.0,169392.0,163673.0,1.126555,1.126555
36,OK,4393809,63787.0,860217.0,0.0,1519146.0,185378.0,40.0,3319920.0,0.0,181944.0,0.345747,0.345747
37,OR,192922,652.0,327164.0,0.0,875020.0,236062.0,0.0,97.0,0.0,192825.0,4.535615,4.535615
38,PA,10101804,307604.0,1937041.0,787083.0,3607506.0,178035.0,1122315.0,8013558.0,787083.0,151449.0,0.357115,0.357115
39,RI,8863,0.0,112499.0,0.0,182950.0,13579.0,0.0,0.0,0.0,8863.0,20.641995,5.000000
40,SC,705705,162323.0,346881.0,581365.0,1603946.0,142486.0,0.0,0.0,581365.0,124341.0,2.272828,2.272828
41,SD,235952,22246.0,99752.0,0.0,347163.0,126540.0,0.0,135.0,0.0,230646.0,1.471329,1.471329
42,TN,501599,202367.0,396870.0,396522.0,2058049.0,115678.0,0.0,3103.0,396522.0,100990.0,4.102977,4.102977
43,TX,27104730,805600.0,5284670.0,425186.0,14137451.0,791211.0,182181.0,14311730.0,425186.0,742124.0,0.521586,0.521586
44,UT,825655,174315.0,298976.0,0.0,853951.0,39674.0,156571.0,318533.0,0.0,29458.0,1.034271,1.034271
45,VA,834458,46785.0,655997.0,310037.0,2435265.0,183979.0,282790.0,87638.0,310037.0,153971.0,2.918379,2.918379
46,VT,19612,0.0,13001.0,0.0,113104.0,22209.0,0.0,0.0,0.0,19612.0,5.767081,5.000000
47,WA,440429,49523.0,403038.0,88163.0,1602662.0,365956.0,0.0,0.0,88163.0,352266.0,3.638866,3.638866
48,WI,275057,219995.0,565025.0,101204.0,1656177.0,150965.0,0.0,0.0,101204.0,173853.0,6.021214,5.000000
49,WV,6089936,472309.0,309019.0,0.0,832806.0,28370.0,2201825.0,3762937.0,0.0,19557.0,0.136751,0.136751
50,WY,5845631,366098.0,181395.0,0.0,499766.0,38474.0,4133004.0,1105416.0,0.0,56163.0,0.085494,0.085494
51,X3,4736995,NaN,NaN,NaN,NaN,NaN,NaN,864135.0,NaN,NaN,NaN,NaN
52,X5,17175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,US,102670531,8169673.0,33609104.0,8098974.0,93557489.0,8187317.0,11766453.0,47577507.0,8098974.0,8369270.0,0.911240,0.911240

In [225]:
import folium
import requests

# -------------------------------
# 1. Load US States GeoJSON
# -------------------------------
geo_url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json"
us_states = requests.get(geo_url).json()

# Use State as index for easy lookup
state_data = merged_df.set_index("State")

# -------------------------------
# 2. Attach merged_df values to GeoJSON features
# -------------------------------
for feature in us_states["features"]:
    st = feature["id"]  # two-letter state code
    if st in state_data.index:
        row = state_data.loc[st]
        feature["properties"].update({
            "State": st,
            "Total Ratio (C/P)": row["total_ratio"],
            "Total Ratio (C/P) Capped": row["total_ratio_capped"],
            "Total Production": row["total_production_2023"],
            "Total Consumption": row["total_consumption_2023"]
        })

# -------------------------------
# 3. Create Choropleth Map (Leaflet)
# -------------------------------
m = folium.Map(
    location=[37.8, -96],
    zoom_start=4,
    tiles="cartodbpositron"  # clean, accessible basemap
)

folium.Choropleth(
    geo_data=us_states,
    data=merged_df,
    columns=["State", "total_ratio_capped"],
    key_on="feature.id",
    fill_color="YlOrRd",      # colorblind-friendly palette
    fill_opacity=0.8,
    line_opacity=0.4,
    nan_fill_color="lightgray",
    legend_name="Total Energy Dependency Ratio (Consumption ÷ Production)"
).add_to(m)

# -------------------------------
# 4. Add tooltips on hover
# -------------------------------
tooltip = folium.features.GeoJsonTooltip(
    fields=[
        "State",
        "Total Ratio (C/P)",
        "Total Ratio (C/P) Capped",
        "Total Production",
        "Total Consumption"
    ],
    aliases=[
        "State:",
        "True Ratio (Consumption ÷ Production):",
        "Capped Ratio (for map scale):",
        "Total Production (BBTU):",
        "Total Consumption (BBTU):"
    ],
    localize=True,
    sticky=True,
    labels=True,
)

folium.GeoJson(
    us_states,
    name="State Details",
    tooltip=tooltip,
    style_function=lambda x: {"fillOpacity": 0, "color": "black", "weight": 0.3}
).add_to(m)

folium.LayerControl().add_to(m)

# -------------------------------
# 5. Display & Save
# -------------------------------
m  # displays the map in Jupyter

m.save("US_Total_Energy_Ratio_Map.html")
print("Map saved as US_Total_Energy_Ratio_Map.html")

Map saved as US_Total_Energy_Ratio_Map.html

In [227]:
import pandas as pd
import numpy as np
import folium
import requests
from folium.features import GeoJsonPopup

# ------------------------------------------------
# 1. Define which columns are energy sources
# ------------------------------------------------
# Map friendly labels -> column names in merged_df
energy_cols = {
    "Coal": "coal_production_2023",
    "Natural Gas": "ng_production_2023",
    "Petroleum": "petroleum_production_2023",      # change if your column name differs
    "Nuclear": "nuclear_production_2023",
    "Renewable": "renewable_production_2023"
}

# (Optional) make sure these columns are numeric
for col in ["total_production_2023", "total_consumption_2023", "total_ratio"] + list(energy_cols.values()):
    if col in merged_df.columns:
        merged_df[col] = pd.to_numeric(merged_df[col], errors="coerce")

# ------------------------------------------------
# 2. Build an HTML popup field for each state
# ------------------------------------------------
def make_popup_html(row):
    # header + totals
    parts = [
        f"<b>{row.name}</b>",
        f"Total Production: {row['total_production_2023']:,.2f} Btu",
        f"Total Consumption: {row['total_consumption_2023']:,.2f} Btu",
        f"Dependency Ratio: {row['total_ratio']*100:.1f}%"
    ]

    # energy mix
    parts.append("Energy Mix (%):")
    mix_lines = []
    total_prod = row["total_production_2023"]

    if pd.notna(total_prod) and total_prod > 0:
        for label, col in energy_cols.items():
            if col in row.index and pd.notna(row[col]):
                share = row[col] / total_prod * 100
                mix_lines.append(f"- {label}: {share:.1f}%")

    if mix_lines:
        parts.extend(mix_lines)

    # join with <br> for HTML line breaks
    return "<br>".join(parts)

# Use state code as index
state_data = merged_df.set_index("State").copy()
state_data["popup_html"] = state_data.apply(make_popup_html, axis=1)

# ------------------------------------------------
# 3. Load GeoJSON and attach popup_html + ratio
# ------------------------------------------------
geo_url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json"
us_states = requests.get(geo_url).json()

for feature in us_states["features"]:
    st = feature["id"]
    if st in state_data.index:
        row = state_data.loc[st]
        feature["properties"].update({
            "popup_html": row["popup_html"],
            "total_ratio_capped": row["total_ratio_capped"]
        })

# ------------------------------------------------
# 4. Make the choropleth + popup
# ------------------------------------------------
m = folium.Map(location=[37.8, -96], zoom_start=4, tiles="cartodbpositron")

folium.Choropleth(
    geo_data=us_states,
    data=merged_df,
    columns=["State", "total_ratio_capped"],
    key_on="feature.id",
    fill_color="YlOrRd",
    fill_opacity=0.8,
    line_opacity=0.4,
    nan_fill_color="lightgray",
    legend_name="Total Energy Dependency Ratio (Consumption ÷ Production)"
).add_to(m)

folium.GeoJson(
    us_states,
    name="State details",
    style_function=lambda x: {"fillOpacity": 0, "color": "black", "weight": 0.3},
    popup=GeoJsonPopup(
        fields=["popup_html"],
        labels=False,              # don't print the field name
        parse_html=True
    ),
).add_to(m)

folium.LayerControl().add_to(m)

m

m.save("US_Total_Energy_Ratio_With_Mix.html")

In [229]:
import folium
import requests
import numpy as np

# ---------------------------------
# 0. Build production/consumption shares
# ---------------------------------
energy_sources = {
    "Coal":        ("coal_production_2023",    "coal_consumption_2023"),
    "Natural Gas": ("ng_production_2023",      "ng_consumption_2023"),
    "Nuclear":     ("nuclear_production_2023", "nuclear_consumption_2023"),
    "Renewable":   ("renewable_production_2023","renewable_consumption_2023"),
    # "Petroleum": ("petroleum_production_2023","petroleum_consumption_2023")  # ← add if you have these
}

for label, (prod_col, cons_col) in energy_sources.items():
    if prod_col in merged_df.columns:
        merged_df[f"{label}_prod_share"] = (
            merged_df[prod_col] / merged_df["total_production_2023"].replace({0: np.nan}) * 100
        )
    if cons_col in merged_df.columns:
        merged_df[f"{label}_cons_share"] = (
            merged_df[cons_col] / merged_df["total_consumption_2023"].replace({0: np.nan}) * 100
        )

# ---------------------------------
# 1. Load US States GeoJSON
# ---------------------------------
geo_url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json"
us_states = requests.get(geo_url).json()

# Use State as index for easy lookup
state_data = merged_df.set_index("State")

# ---------------------------------
# 2. Attach merged_df values + shares to GeoJSON features
# ---------------------------------
for feature in us_states["features"]:
    st = feature["id"]  # two-letter state code
    if st in state_data.index:
        row = state_data.loc[st]

        props = {
            "State": st,
            "Total Ratio (C/P)": row["total_ratio"],
            "Total Ratio (C/P) Capped": row["total_ratio_capped"],
            "Total Production": row["total_production_2023"],
            "Total Consumption": row["total_consumption_2023"],
        }

        # add production/consumption mix %
        for label in energy_sources.keys():
            prod_key = f"{label}_prod_share"
            cons_key = f"{label}_cons_share"
            if prod_key in row.index:
                props[f"{label} Prod %"] = row[prod_key]
            if cons_key in row.index:
                props[f"{label} Cons %"] = row[cons_key]

        feature["properties"].update(props)

# ---------------------------------
# 3. Create Choropleth Map (Leaflet)
# ---------------------------------
m = folium.Map(
    location=[37.8, -96],
    zoom_start=4,
    tiles="cartodbpositron"  # clean, accessible basemap
)

folium.Choropleth(
    geo_data=us_states,
    data=merged_df,
    columns=["State", "total_ratio_capped"],
    key_on="feature.id",
    fill_color="YlOrRd",      # colorblind-friendly palette
    fill_opacity=0.8,
    line_opacity=0.4,
    nan_fill_color="lightgray",
    legend_name="Total Energy Dependency Ratio (Consumption ÷ Production)"
).add_to(m)

# ---------------------------------
# 4. Add tooltips on hover (now including mix %)
# ---------------------------------
fields = [
    "State",
    "Total Ratio (C/P)",
    "Total Ratio (C/P) Capped",
    "Total Production",
    "Total Consumption",
]

aliases = [
    "State:",
    "True Ratio (Consumption ÷ Production):",
    "Capped Ratio (for map scale):",
    "Total Production (BBTU):",
    "Total Consumption (BBTU):",
]

# add dynamic energy mix fields
for label in energy_sources.keys():
    fields.extend([f"{label} Prod %", f"{label} Cons %"])
    aliases.extend([
        f"{label} Share of Production (%):",
        f"{label} Share of Consumption (%):",
    ])

tooltip = folium.features.GeoJsonTooltip(
    fields=fields,
    aliases=aliases,
    localize=True,
    sticky=True,
    labels=True,
)

folium.GeoJson(
    us_states,
    name="State Details",
    tooltip=tooltip,
    style_function=lambda x: {"fillOpacity": 0, "color": "black", "weight": 0.3}
).add_to(m)

folium.LayerControl().add_to(m)

# ---------------------------------
# 5. Display & Save
# ---------------------------------
m  # displays the map in Jupyter

m.save("US_Total_Energy_Ratio_Map_with_Mix.html")
print("Map saved as US_Total_Energy_Ratio_Map_with_Mix.html")

Map saved as US_Total_Energy_Ratio_Map_with_Mix.html

In [231]:
import pandas as pd
import numpy as np
import folium
import requests

# ============================================
# 1. CLEAN NUMERIC COLUMNS (SAFE STEP)
# ============================================
num_cols = [c for c in merged_df.columns if c != "State"]

for col in num_cols:
    merged_df[col] = (
        merged_df[col]
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
    )
    merged_df[col] = pd.to_numeric(merged_df[col], errors="coerce")

# ============================================
# 2. TOTAL RATIO (CONSUMPTION / PRODUCTION)
# ============================================
merged_df["total_ratio"] = (
    merged_df["total_consumption_2023"] /
    merged_df["total_production_2023"].replace({0: np.nan})
)

merged_df["total_ratio_capped"] = merged_df["total_ratio"].clip(upper=5)

# ============================================
# 3. CREATE "OTHER" CATEGORIES (RESIDUAL)
# ============================================
# Other Consumption = total - (coal + gas + nuclear + renewables)
merged_df["other_consumption_2023"] = (
    merged_df["total_consumption_2023"]
    - (
        merged_df["coal_consumption_2023"] +
        merged_df["ng_consumption_2023"] +
        merged_df["nuclear_consumption_2023"] +
        merged_df["renewable_consumption_2023"]
    )
).clip(lower=0)

# Other Production = total - (coal + gas + nuclear + renewables)
merged_df["other_production_2023"] = (
    merged_df["total_production_2023"]
    - (
        merged_df["coal_production_2023"] +
        merged_df["ng_production_2023"] +
        merged_df["nuclear_production_2023"] +
        merged_df["renewable_production_2023"]
    )
).clip(lower=0)

# ============================================
# 4. COMPUTE SHARES (% OF TOTAL) FOR EACH FUEL
# ============================================
# Consumption shares
merged_df["Coal Cons %"]        = merged_df["coal_consumption_2023"]      / merged_df["total_consumption_2023"] * 100
merged_df["Natural Gas Cons %"] = merged_df["ng_consumption_2023"]        / merged_df["total_consumption_2023"] * 100
merged_df["Nuclear Cons %"]     = merged_df["nuclear_consumption_2023"]   / merged_df["total_consumption_2023"] * 100
merged_df["Renewable Cons %"]   = merged_df["renewable_consumption_2023"] / merged_df["total_consumption_2023"] * 100
merged_df["Other Cons %"]       = merged_df["other_consumption_2023"]     / merged_df["total_consumption_2023"] * 100

# Production shares
merged_df["Coal Prod %"]        = merged_df["coal_production_2023"]       / merged_df["total_production_2023"] * 100
merged_df["Natural Gas Prod %"] = merged_df["ng_production_2023"]         / merged_df["total_production_2023"] * 100
merged_df["Nuclear Prod %"]     = merged_df["nuclear_production_2023"]    / merged_df["total_production_2023"] * 100
merged_df["Renewable Prod %"]   = merged_df["renewable_production_2023"]  / merged_df["total_production_2023"] * 100
merged_df["Other Prod %"]       = merged_df["other_production_2023"]      / merged_df["total_production_2023"] * 100

# ============================================
# 5. LOAD US STATES GEOJSON
# ============================================
geo_url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json"
us_states = requests.get(geo_url).json()

state_data = merged_df.set_index("State")

# Attach all needed props to each state feature
for feature in us_states["features"]:
    st = feature["id"]  # state code
    if st in state_data.index:
        row = state_data.loc[st]
        feature["properties"].update({
            "State": st,
            "Total Ratio (C/P)": row["total_ratio"],
            "Total Ratio (C/P) Capped": row["total_ratio_capped"],
            "Total Production": row["total_production_2023"],
            "Total Consumption": row["total_consumption_2023"],
            "Coal Prod %":        row["Coal Prod %"],
            "Coal Cons %":        row["Coal Cons %"],
            "Natural Gas Prod %": row["Natural Gas Prod %"],
            "Natural Gas Cons %": row["Natural Gas Cons %"],
            "Nuclear Prod %":     row["Nuclear Prod %"],
            "Nuclear Cons %":     row["Nuclear Cons %"],
            "Renewable Prod %":   row["Renewable Prod %"],
            "Renewable Cons %":   row["Renewable Cons %"],
            "Other Prod %":       row["Other Prod %"],
            "Other Cons %":       row["Other Cons %"],
        })

# ============================================
# 6. BUILD CHOROPLETH MAP
# ============================================
m = folium.Map(
    location=[37.8, -96],
    zoom_start=4,
    tiles="cartodbpositron"
)

folium.Choropleth(
    geo_data=us_states,
    data=merged_df,
    columns=["State", "total_ratio_capped"],
    key_on="feature.id",
    fill_color="YlOrRd",
    fill_opacity=0.8,
    line_opacity=0.4,
    nan_fill_color="lightgray",
    legend_name="Total Energy Dependency Ratio (Consumption ÷ Production)"
).add_to(m)

# ============================================
# 7. TOOLTIP WITH FULL MIX INCLUDING "OTHER"
# ============================================
fields = [
    "State",
    "Total Ratio (C/P)",
    "Total Ratio (C/P) Capped",
    "Total Production",
    "Total Consumption",
    "Coal Prod %",
    "Coal Cons %",
    "Natural Gas Prod %",
    "Natural Gas Cons %",
    "Nuclear Prod %",
    "Nuclear Cons %",
    "Renewable Prod %",
    "Renewable Cons %",
    "Other Prod %",
    "Other Cons %",
]

aliases = [
    "State:",
    "True Ratio (Consumption ÷ Production):",
    "Capped Ratio (for map scale):",
    "Total Production (BBTU):",
    "Total Consumption (BBTU):",
    "Coal Share of Production (%):",
    "Coal Share of Consumption (%):",
    "Natural Gas Share of Production (%):",
    "Natural Gas Share of Consumption (%):",
    "Nuclear Share of Production (%):",
    "Nuclear Share of Consumption (%):",
    "Renewable Share of Production (%):",
    "Renewable Share of Consumption (%):",
    "Other Share of Production (%):",
    "Other Share of Consumption (%):",
]

tooltip = folium.features.GeoJsonTooltip(
    fields=fields,
    aliases=aliases,
    localize=True,
    sticky=True,
    labels=True,
)

folium.GeoJson(
    us_states,
    name="State Details",
    tooltip=tooltip,
    style_function=lambda x: {"fillOpacity": 0, "color": "black", "weight": 0.3},
).add_to(m)

folium.LayerControl().add_to(m)

# ============================================
# 8. DISPLAY & SAVE
# ============================================
m  # display in Jupyter

m.save("US_Total_Energy_Ratio_Map_with_Other.html")
print("Map saved as US_Total_Energy_Ratio_Map_with_Other.html")

Map saved as US_Total_Energy_Ratio_Map_with_Other.html

In [237]:
import pandas as pd
import numpy as np
import folium
import requests

# ============================================
# 1. CLEAN NUMERIC COLUMNS (SAFE STEP)
# ============================================
num_cols = [c for c in merged_df.columns if c != "State"]

for col in num_cols:
    merged_df[col] = (
        merged_df[col]
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
    )
    merged_df[col] = pd.to_numeric(merged_df[col], errors="coerce")

# ============================================
# 2. TOTAL RATIO (CONSUMPTION / PRODUCTION)
# ============================================
merged_df["total_ratio"] = (
    merged_df["total_consumption_2023"] /
    merged_df["total_production_2023"].replace({0: np.nan})
)

merged_df["total_ratio_capped"] = merged_df["total_ratio"].clip(upper=5)

# ============================================
# 3. CREATE "OTHER" CATEGORIES (RESIDUAL)
# ============================================
# Other Consumption = total - (coal + gas + nuclear + renewables)
merged_df["other_consumption_2023"] = (
    merged_df["total_consumption_2023"]
    - (
        merged_df["coal_consumption_2023"] +
        merged_df["ng_consumption_2023"] +
        merged_df["nuclear_consumption_2023"] +
        merged_df["renewable_consumption_2023"]
    )
).clip(lower=0)

# Other Production = total - (coal + gas + nuclear + renewables)
merged_df["other_production_2023"] = (
    merged_df["total_production_2023"]
    - (
        merged_df["coal_production_2023"] +
        merged_df["ng_production_2023"] +
        merged_df["nuclear_production_2023"] +
        merged_df["renewable_production_2023"]
    )
).clip(lower=0)

# ============================================
# 4. COMPUTE SHARES (% OF TOTAL) FOR EACH FUEL
# ============================================
# Consumption shares
merged_df["Coal Cons %"]        = merged_df["coal_consumption_2023"]      / merged_df["total_consumption_2023"] * 100
merged_df["Natural Gas Cons %"] = merged_df["ng_consumption_2023"]        / merged_df["total_consumption_2023"] * 100
merged_df["Nuclear Cons %"]     = merged_df["nuclear_consumption_2023"]   / merged_df["total_consumption_2023"] * 100
merged_df["Renewable Cons %"]   = merged_df["renewable_consumption_2023"] / merged_df["total_consumption_2023"] * 100
merged_df["Other Cons %"]       = merged_df["other_consumption_2023"]     / merged_df["total_consumption_2023"] * 100

# Production shares
merged_df["Coal Prod %"]        = merged_df["coal_production_2023"]       / merged_df["total_production_2023"] * 100
merged_df["Natural Gas Prod %"] = merged_df["ng_production_2023"]         / merged_df["total_production_2023"] * 100
merged_df["Nuclear Prod %"]     = merged_df["nuclear_production_2023"]    / merged_df["total_production_2023"] * 100
merged_df["Renewable Prod %"]   = merged_df["renewable_production_2023"]  / merged_df["total_production_2023"] * 100
merged_df["Other Prod %"]       = merged_df["other_production_2023"]      / merged_df["total_production_2023"] * 100

# ============================================
# 5. ROUND SHARES TO NEAREST WHOLE NUMBER
# ============================================
share_cols = [
    "Coal Cons %","Natural Gas Cons %","Nuclear Cons %","Renewable Cons %","Other Cons %",
    "Coal Prod %","Natural Gas Prod %","Nuclear Prod %","Renewable Prod %","Other Prod %"
]

for col in share_cols:
    merged_df[col] = merged_df[col].round(0)

# ============================================
# 6. LOAD US STATES GEOJSON
# ============================================
geo_url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json"
us_states = requests.get(geo_url).json()

state_data = merged_df.set_index("State")

# Attach all needed props to each state feature
for feature in us_states["features"]:
    st = feature["id"]  # state code
    if st in state_data.index:
        row = state_data.loc[st]
        feature["properties"].update({
            "State": st,
            "Total Ratio (C/P)": row["total_ratio"],
            "Total Ratio (C/P) Capped": row["total_ratio_capped"],
            "Total Production": row["total_production_2023"],
            "Total Consumption": row["total_consumption_2023"],

            # Heading for the block
            "Energy Mix (%)": "",

            # Indented energy mix entries
            "    Coal Prod %":        row["Coal Prod %"],
            "    Coal Cons %":        row["Coal Cons %"],
            "    Natural Gas Prod %": row["Natural Gas Prod %"],
            "    Natural Gas Cons %": row["Natural Gas Cons %"],
            "    Nuclear Prod %":     row["Nuclear Prod %"],
            "    Nuclear Cons %":     row["Nuclear Cons %"],
            "    Renewable Prod %":   row["Renewable Prod %"],
            "    Renewable Cons %":   row["Renewable Cons %"],
            "    Other Prod %":       row["Other Prod %"],
            "    Other Cons %":       row["Other Cons %"],
        })

# ============================================
# 7. BUILD CHOROPLETH MAP
# ============================================
m = folium.Map(
    location=[37.8, -96],
    zoom_start=4,
    tiles="cartodbpositron"
)

folium.Choropleth(
    geo_data=us_states,
    data=merged_df,
    columns=["State", "total_ratio_capped"],
    key_on="feature.id",
    fill_color="YlOrRd",
    fill_opacity=0.8,
    line_opacity=0.4,
    nan_fill_color="lightgray",
    legend_name="Total Energy Dependency Ratio (Consumption ÷ Production)"
).add_to(m)

# ============================================
# 8. TOOLTIP WITH HEADING + INDENTED MIX
# ============================================
tooltip = folium.features.GeoJsonTooltip(
    fields=[
        "State",
        "Total Ratio (C/P)",
        "Total Ratio (C/P) Capped",
        "Total Production",
        "Total Consumption",

        "Energy Mix (%)",   # heading line

        "    Coal Prod %",
        "    Coal Cons %",
        "    Natural Gas Prod %",
        "    Natural Gas Cons %",
        "    Nuclear Prod %",
        "    Nuclear Cons %",
        "    Renewable Prod %",
        "    Renewable Cons %",
        "    Other Prod %",
        "    Other Cons %",
    ],
    aliases=[
        "<u>STATE:</u>",
        "True Ratio (Consumption ÷ Production):",
        "Capped Ratio (for map scale):",
        "Total Production (BBTU):",
        "Total Consumption (BBTU):",

        "<u>ENERGY MIX(%):</u>",

        "    Coal Share of Production (%):",
        "    Coal Share of Consumption (%):",
        "    Natural Gas Share of Production (%):",
        "    Natural Gas Share of Consumption (%):",
        "    Nuclear Share of Production (%):",
        "    Nuclear Share of Consumption (%):",
        "    Renewable Share of Production (%):",
        "    Renewable Share of Consumption (%):",
        "    Other Share of Production (%):",
        "    Other Share of Consumption (%):",
    ],
    localize=True,
    sticky=True,
    labels=True
)

folium.GeoJson(
    us_states,
    name="State Details",
    tooltip=tooltip,
    style_function=lambda x: {"fillOpacity": 0, "color": "black", "weight": 0.3},
).add_to(m)

folium.LayerControl().add_to(m)

# ============================================
# 9. DISPLAY & SAVE
# ============================================
m  # display in Jupyter

m.save("US_Total_Energy_Ratio_Map_with_Other_rounded.html")
print("Map saved as US_Total_Energy_Ratio_Map_with_Other_rounded.html")

Map saved as US_Total_Energy_Ratio_Map_with_Other_rounded.html